channels:
  # Define conda channels here. 
  - conda-forge

dependencies:
  # Define conda packages here. 
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search  
  - scrapy=2.5.0
  - selenium=3.141.0
  - pycodestyle=2.7.0
  - twisted=21.7.0
  - python=3.7.5
  - pip=20.1
  - pip:
    # Define pip packages here. 
    # https://pypi.org/
    - rpaframework==10.3.0 # https://rpaframework.org/releasenotes.html
